# Copyright © 2022 Montgomery Edwards⁴⁴⁸ (github.com/x448)
# This file is licensed under the MIT License.
#
# github.com/x448/helix-config-toml
# A post-modern Helix editor configuration (config.toml) for new users.
#
# The ~15 settings in this config help new users avoid some problems and
# show how to configure Helix editor with useful examples.
#
# Notably, this config makes pressing escape reset Helix to default state,
# the way new users and reviewers expect as mentioned at:
# - https://github.com/helix-editor/helix/pull/5289
# - https://www.youtube.com/watch?v=8L308PdmhMY&t=887s
#
# Instructions:
# - Linux, macOS, *BSD: copy this file to ~/.config/helix/config.toml
# - Windows: copy this file to %AppData%\helix\config.toml
#
# This config makes Helix editor:
# - Map esc key to reset Helix to fully default state of:
#   normal mode, single cursor, not having multiple chars selected.
#   NOTE: Some advanced Helix users dislike this shortcut and they prefer to
#   use distinct keys (extra steps) to escape back to fully default state.
# - Use dark_plus theme, which works without any problems in hx --tutor
#   and looks familiar to users of "Dark+" theme in Visual Studio Code.
# - Make cursor shape indicate normal, insert, and select modes.
# - Fix true color detection problem on some platforms.
# - etc.

# As of Helix 22.12, most themes don't seem to work well with hx --tutor.
# See https://github.com/helix-editor/helix/pull/5309
theme = "dark_plus"  # dark_plus works well with hx --tutor.

[editor]
color-modes = true
line-number = "relative"
mouse = false

# Resolve true color detection problems (e.g. on Linux in Windows WSL2)
# such as the error, "theme: theme requires true color support".
true-color = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
ret = ["move_line_down", "goto_first_nonwhitespace"]
0   = "goto_line_start"

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
0   = "goto_line_start"
